export const LOGIN_SUCCESS = "LOGIN_SUCCESS";
export const LOGIN_FAIL = "LOGIN_FAIL";
export const LOG_OUT = "LOG_OUT";

export const CUSTOM_INPUT = "CUSTOM_INPUT";

export const GET_PROVINSI_SUCCESS = "GET_PROVINSI_SUCCESS";
export const GET_PROVINSI_FAIL = "GET_PROVINSI_FAIL";

export const GET_KOTA_SUCCESS = "GET_KOTA_SUCCESS";
export const GET_KOTA_FAIL = "GET_KOTA_FAIL";

export const GET_KECAMATAN_SUCCESS = "GET_KECAMATAN_SUCCESS";
export const GET_KECAMATAN_FAIL = "GET_KECAMATAN_FAIL";

export const GET_KELURAHAN_SUCCESS = "GET_KELURAHAN_SUCCESS";
export const GET_KELURAHAN_FAIL = "GET_KELURAHAN_FAIL";

export const UPLOAD_STORAGE_SUCCESS = "UPLOAD_STORAGE_SUCCESS";
export const UPLOAD_STORAGE_FAIL = "UPLOAD_STORAGE_FAIL";
